var searchData=
[
  ['main',['main',['../generalgraph_8cpp.html#a0ddf1224851353fc92bfbff6f499fa97',1,'generalgraph.cpp']]],
  ['markdofsonboundary',['MarkDofsOnBoundary',['../namespacesmoothg.html#a6227fc30ba428ab9d49ac84b28d6dcb3',1,'smoothg']]],
  ['matrixutilities_2ecpp',['MatrixUtilities.cpp',['../MatrixUtilities_8cpp.html',1,'']]],
  ['matrixutilities_2ehpp',['MatrixUtilities.hpp',['../MatrixUtilities_8hpp.html',1,'']]],
  ['maxnorm',['MaxNorm',['../namespacesmoothg.html#af48002c1039dcb0c8301b45364394c9c',1,'smoothg']]],
  ['metisgraphpartitioner',['MetisGraphPartitioner',['../classsmoothg_1_1MetisGraphPartitioner.html',1,'smoothg']]],
  ['metisgraphpartitioner',['MetisGraphPartitioner',['../classsmoothg_1_1MetisGraphPartitioner.html#a49ff3d753d3464ebbc3d33add5836685',1,'smoothg::MetisGraphPartitioner']]],
  ['metisgraphpartitioner_2ecpp',['MetisGraphPartitioner.cpp',['../MetisGraphPartitioner_8cpp.html',1,'']]],
  ['metisgraphpartitioner_2ehpp',['MetisGraphPartitioner.hpp',['../MetisGraphPartitioner_8hpp.html',1,'']]],
  ['minresblocksolver',['MinresBlockSolver',['../classsmoothg_1_1MinresBlockSolver.html',1,'smoothg']]],
  ['minresblocksolver',['MinresBlockSolver',['../classsmoothg_1_1MinresBlockSolver.html#aa343d2aa5652e79a24d2c81107bf868a',1,'smoothg::MinresBlockSolver::MinresBlockSolver(MPI_Comm comm, mfem::HypreParMatrix *M, mfem::HypreParMatrix *D, mfem::HypreParMatrix *W, const mfem::Array&lt; int &gt; &amp;block_true_offsets, bool use_W=false)'],['../classsmoothg_1_1MinresBlockSolver.html#a2498d505ca99d8d13a6d26fb5ec40bde',1,'smoothg::MinresBlockSolver::MinresBlockSolver(MPI_Comm comm, const MixedMatrix &amp;mgL)']]],
  ['minresblocksolver_2ecpp',['MinresBlockSolver.cpp',['../MinresBlockSolver_8cpp.html',1,'']]],
  ['minresblocksolver_2ehpp',['MinresBlockSolver.hpp',['../MinresBlockSolver_8hpp.html',1,'']]],
  ['minresblocksolverfalse',['MinresBlockSolverFalse',['../classsmoothg_1_1MinresBlockSolverFalse.html#ae845b881bd1d37fce67a38e486a626fc',1,'smoothg::MinresBlockSolverFalse']]],
  ['minresblocksolverfalse',['MinresBlockSolverFalse',['../classsmoothg_1_1MinresBlockSolverFalse.html',1,'smoothg']]],
  ['mixed_5fgl_5fcoarsener',['Mixed_GL_Coarsener',['../classsmoothg_1_1Mixed__GL__Coarsener.html',1,'smoothg']]],
  ['mixed_5fgl_5fcoarsener',['Mixed_GL_Coarsener',['../classsmoothg_1_1Mixed__GL__Coarsener.html#abef7378e553b39cb2cdd3227f429259c',1,'smoothg::Mixed_GL_Coarsener']]],
  ['mixed_5fgl_5fcoarsener_2ecpp',['Mixed_GL_Coarsener.cpp',['../Mixed__GL__Coarsener_8cpp.html',1,'']]],
  ['mixed_5fgl_5fcoarsener_2ehpp',['Mixed_GL_Coarsener.hpp',['../Mixed__GL__Coarsener_8hpp.html',1,'']]],
  ['mixedlaplaciansolver',['MixedLaplacianSolver',['../classsmoothg_1_1MixedLaplacianSolver.html',1,'smoothg']]],
  ['mixedlaplaciansolver_2ecpp',['MixedLaplacianSolver.cpp',['../MixedLaplacianSolver_8cpp.html',1,'']]],
  ['mixedlaplaciansolver_2ehpp',['MixedLaplacianSolver.hpp',['../MixedLaplacianSolver_8hpp.html',1,'']]],
  ['mixedmatrix',['MixedMatrix',['../classsmoothg_1_1MixedMatrix.html#a1ef150c883a700a77b82fbb83b6c9787',1,'smoothg::MixedMatrix::MixedMatrix(const mfem::SparseMatrix &amp;vertex_edge, const mfem::Vector &amp;weight, const mfem::HypreParMatrix &amp;edge_d_td, DistributeWeight dist_weight=DistributeWeight::True)'],['../classsmoothg_1_1MixedMatrix.html#a636069c74323864e890e79f53f2e475e',1,'smoothg::MixedMatrix::MixedMatrix(const mfem::SparseMatrix &amp;vertex_edge, const mfem::HypreParMatrix &amp;edge_d_td)'],['../classsmoothg_1_1MixedMatrix.html#ac540da04c988d48c1144c2ffa4370360',1,'smoothg::MixedMatrix::MixedMatrix(std::unique_ptr&lt; mfem::SparseMatrix &gt; M, std::unique_ptr&lt; mfem::SparseMatrix &gt; D, const mfem::HypreParMatrix &amp;edge_d_td)'],['../classsmoothg_1_1MixedMatrix.html#a918f88e1bd19f00a986a2508351c54c5',1,'smoothg::MixedMatrix::MixedMatrix(std::unique_ptr&lt; mfem::SparseMatrix &gt; M, std::unique_ptr&lt; mfem::SparseMatrix &gt; D, std::unique_ptr&lt; mfem::SparseMatrix &gt; W, const mfem::HypreParMatrix &amp;edge_d_td)'],['../classsmoothg_1_1MixedMatrix.html#a2a5fef0bd30cb6c0f207c8bbde260023',1,'smoothg::MixedMatrix::MixedMatrix(const MixedMatrix &amp;fine_mgL, const mfem::SparseMatrix &amp;Pu, const mfem::SparseMatrix &amp;Pp, const mfem::HypreParMatrix &amp;edge_d_td)']]],
  ['mixedmatrix',['MixedMatrix',['../classsmoothg_1_1MixedMatrix.html',1,'smoothg']]],
  ['mixedmatrix_2ecpp',['MixedMatrix.cpp',['../MixedMatrix_8cpp.html',1,'']]],
  ['mixedmatrix_2ehpp',['MixedMatrix.hpp',['../MixedMatrix_8hpp.html',1,'']]],
  ['mpi_5fsession',['mpi_session',['../structsmoothg_1_1mpi__session.html',1,'smoothg']]],
  ['mult',['Mult',['../classsmoothg_1_1HybridSolver.html#a4c61c7839e6afa91b89190df1b013214',1,'smoothg::HybridSolver::Mult()'],['../classsmoothg_1_1LocalGraphEdgeSolver.html#a0888a65715204a2f1c83d39a63e55356',1,'smoothg::LocalGraphEdgeSolver::Mult(const mfem::Vector &amp;rhs, mfem::Vector &amp;sol_sigma)'],['../classsmoothg_1_1LocalGraphEdgeSolver.html#a17fa9c10cfc9b7a5d72e992b5f4e2ed1',1,'smoothg::LocalGraphEdgeSolver::Mult(const mfem::Vector &amp;rhs, mfem::Vector &amp;sol_sigma, mfem::Vector &amp;sol_u)'],['../classsmoothg_1_1MinresBlockSolver.html#a8747e3706d884a29d00d065d3edd1c8a',1,'smoothg::MinresBlockSolver::Mult()'],['../classsmoothg_1_1MinresBlockSolverFalse.html#a8b0cbc7036da516d3a5199d123d15862',1,'smoothg::MinresBlockSolverFalse::Mult()'],['../classsmoothg_1_1Upscale.html#aca86c576dcf9eec88fd2f258217bf3be',1,'smoothg::Upscale::Mult()'],['../namespacesmoothg.html#a73f21a9a7d1292763ed8d1343ba02ddc',1,'smoothg::Mult()']]],
  ['mult_5fa_5fvvt',['Mult_a_VVt',['../namespacesmoothg.html#a78aa208a6e56502beb7962055df7684e',1,'smoothg']]],
  ['multsparsedense',['MultSparseDense',['../namespacesmoothg.html#a8462c47e554826e19abcf3f9e42f277c',1,'smoothg']]],
  ['multsparsedensetranspose',['MultSparseDenseTranspose',['../namespacesmoothg.html#ac24b00fa9f7f31b0d18a12ce09fca656',1,'smoothg']]]
];
